// Automatically generated by SUtools, editing not advised.
#ifndef R_CONTREE_H
#define R_CONTREE_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("conTree", String)
#else
#define _(String) (String)
#endif

extern SEXP store_rfun(SEXP rfun);
static const R_CallMethodDef CallEntries[] = {
  {"store_rfun", (DL_FUNC) &store_rfun, 1},
  {NULL, NULL, 0}
};

#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}

void F77_SUB(set_miss)(
double *arg
);
 
static R_NativePrimitiveArgType set_miss_t[] = {
REALSXP
};
void F77_SUB(set_trm)(
int *irg
);
 
static R_NativePrimitiveArgType set_trm_t[] = {
INTSXP
};
void F77_SUB(set_ntn)(
int *irg
);
 
static R_NativePrimitiveArgType set_ntn_t[] = {
INTSXP
};
void F77_SUB(set_qint)(
int *irg
);
 
static R_NativePrimitiveArgType set_qint_t[] = {
INTSXP
};
void F77_SUB(set_pwr)(
double *arg
);
 
static R_NativePrimitiveArgType set_pwr_t[] = {
REALSXP
};
void F77_SUB(set_cri)(
int *irg
);
 
static R_NativePrimitiveArgType set_cri_t[] = {
INTSXP
};
void F77_SUB(set_samp)(
int *irg
);
 
static R_NativePrimitiveArgType set_samp_t[] = {
INTSXP
};
void F77_SUB(set_kri)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_kri_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(set_qqtrm)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_qqtrm_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(set_quant)(
double *arg
);
 
static R_NativePrimitiveArgType set_quant_t[] = {
REALSXP
};
void F77_SUB(set_vrb)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_vrb_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(classin)(
int *ient,
int *nclasssv,
double *costssv,
int *nout,
double *out
);
 
static R_NativePrimitiveArgType classin_t[] = {
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(fcontrast)(
int *no,
int *ni,
double *x,
double *y,
double *y2,
double *z,
double *w,
int *lx,
int *mxt,
int *itre,
double *rtre,
int *mxc,
double *cat,
int *ms,
int *isc
);
 
static R_NativePrimitiveArgType fcontrast_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP
};
void F77_SUB(get_stor)(
int *irg1,
int *irg2
);
 
static R_NativePrimitiveArgType get_stor_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(prune1)(
int *itr,
double *rtr,
int *nodes,
double *thr,
int *itro,
double *rtro
);
 
static R_NativePrimitiveArgType prune1_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(crinode)(
int *itr,
double *rtr,
int *mxnodes,
int *node,
int *nodes,
double *cri,
double *wt
);
 
static R_NativePrimitiveArgType crinode_t[] = {
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP
};
void F77_SUB(getnodes1)(
int *no,
int *ni,
double *x,
int *itre,
double *rtre,
double *cat,
int *nodes
);
 
static R_NativePrimitiveArgType getnodes1_t[] = {
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP
};
void F77_SUB(getlims)(
int *node,
int *ni,
int *itr,
double *rtr,
double *cat,
int *nvar,
int *jvar,
double *vlims,
int *jerr
);
 
static R_NativePrimitiveArgType getlims_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP
};
void F77_SUB(andarm)(
int *n,
double *y,
double *y2,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(fintcdf1)(
int *n,
double *y,
int *m,
double *b,
double *w1,
int *nit,
double *thr,
double *cdf,
int *jt,
double *err
);
 
static R_NativePrimitiveArgType fintcdf1_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(cdfpoints1)(
int *m,
double *x,
int *n,
double *y,
double *w,
double *cdf
);
 
static R_NativePrimitiveArgType cdfpoints1_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(trans)(
int *ny,
double *y,
double *wy,
int *nz,
double *z,
double *wz,
int *nt,
double *t
);
 
static R_NativePrimitiveArgType trans_t[] = {
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(untie)(
int *n,
double *y,
double *u
);
 
static R_NativePrimitiveArgType untie_t[] = {
INTSXP,
REALSXP,
REALSXP
};

static R_FortranMethodDef fMethods[] = {
FDEF(set_miss) ,
FDEF(set_trm) ,
FDEF(set_ntn) ,
FDEF(set_qint) ,
FDEF(set_pwr) ,
FDEF(set_cri) ,
FDEF(set_samp) ,
FDEF(set_kri) ,
FDEF(set_qqtrm) ,
FDEF(set_quant) ,
FDEF(set_vrb) ,
FDEF(classin) ,
FDEF(fcontrast) ,
FDEF(get_stor) ,
FDEF(prune1) ,
FDEF(crinode) ,
FDEF(getnodes1) ,
FDEF(getlims) ,
FDEF(andarm) ,
FDEF(fintcdf1) ,
FDEF(cdfpoints1) ,
FDEF(trans) ,
FDEF(untie) ,
{NULL, NULL, 0}
};

void R_init_conTree(DllInfo *dll){
  R_registerRoutines(dll, NULL, CallEntries, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
